/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentAndTag;

import forConnection.connect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sajee
 */
public class addTags extends javax.swing.JFrame {

    /**
     * Creates new form addTags
     */
    public addTags() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddTag1 = new javax.swing.JButton();
        btnmanageTag = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTagName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAddTag = new javax.swing.JButton();
        txtTagCode = new javax.swing.JComboBox<>();
        txtRelatedTag = new javax.swing.JComboBox<>();
        btnAddTag2 = new javax.swing.JButton();

        btnAddTag1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddTag1.setForeground(new java.awt.Color(10, 139, 10));
        btnAddTag1.setText("Save");
        btnAddTag1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 189, 18), 4, true));
        btnAddTag1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTag1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnmanageTag.setBackground(new java.awt.Color(243, 206, 152));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Tags");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name Of Tag :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Code Of Tag :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Related Tag :");

        txtTagName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagNameActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(187, 22, 22));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(198, 24, 24), 4, true));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddTag.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddTag.setForeground(new java.awt.Color(10, 139, 10));
        btnAddTag.setText("Save");
        btnAddTag.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 189, 18), 4, true));
        btnAddTag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTagActionPerformed(evt);
            }
        });

        txtTagCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "lec_01", "tute_02", "lab_03" }));

        txtRelatedTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "LECTURE", "TUTORIAL", "LAB" }));

        btnAddTag2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddTag2.setForeground(new java.awt.Color(61, 61, 206));
        btnAddTag2.setText("Go To Modify   >>>");
        btnAddTag2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(136, 136, 221), 4, true));
        btnAddTag2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTag2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnmanageTagLayout = new javax.swing.GroupLayout(btnmanageTag);
        btnmanageTag.setLayout(btnmanageTagLayout);
        btnmanageTagLayout.setHorizontalGroup(
            btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmanageTagLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(233, 233, 233))
            .addGroup(btnmanageTagLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btnmanageTagLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddTag, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnmanageTagLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRelatedTag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(btnmanageTagLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTagCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(btnmanageTagLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTagName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnmanageTagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTag2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnmanageTagLayout.setVerticalGroup(
            btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmanageTagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTagName, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(btnmanageTagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAddTag))
                .addGap(52, 52, 52)
                .addComponent(btnAddTag2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmanageTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmanageTag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTagActionPerformed
        
       String tName = txtTagName.getText().toString();
       String tCode = txtTagCode.getSelectedItem().toString();
       String rTag = txtRelatedTag.getSelectedItem().toString();
       
        if( tName.isEmpty() )
            JOptionPane.showMessageDialog(null, "Please Enter Tag Name.");
        else if(tCode.isEmpty())
            JOptionPane.showMessageDialog(null, "Please Select Tag Code from ComboBox.");
        else if(rTag.isEmpty())
            JOptionPane.showMessageDialog(null, "Please Select Related Tag from ComboBox.");
        else
        {
               try {
                     connect obj = new connect(); 
                     Connection conn = obj.getConnection();

                    String query = " insert into tag (TagName, TagCode, RelatedTag)" +" values(?,?,?)";
                    PreparedStatement pState = conn.prepareStatement(query);
                    pState.setString(1, tName);
                    pState.setString(2, tCode);
                    pState.setString(3, rTag);
                    
                    int response = JOptionPane.showConfirmDialog(null, "Do you want to Save?", "INSERT", JOptionPane.YES_NO_OPTION);
                    if(response == JOptionPane.YES_OPTION)
                    {
                        pState.execute(); 
                        JOptionPane.showMessageDialog(null,"data successfully added.");
                    }
                    conn.close();

                } catch (SQLException ex) {

                    System.err.println("Got an exception!");                              
                    JOptionPane.showConfirmDialog(null, ex.getMessage());

                }
        }
    
    }//GEN-LAST:event_btnAddTagActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        homeForStudentAndTag homePage = new homeForStudentAndTag();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtTagNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagNameActionPerformed

    private void btnAddTag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTag1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTag1ActionPerformed

    private void btnAddTag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTag2ActionPerformed
        manageTag managePage = new manageTag();
        managePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddTag2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTags.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTags().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTag;
    private javax.swing.JButton btnAddTag1;
    private javax.swing.JButton btnAddTag2;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel btnmanageTag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> txtRelatedTag;
    private javax.swing.JComboBox<String> txtTagCode;
    private javax.swing.JTextField txtTagName;
    // End of variables declaration//GEN-END:variables
}
