/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentAndTag;

import forConnection.connect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sajee
 */
public class manageTag extends javax.swing.JFrame {
    connect cObj = new connect(); 
    PreparedStatement pst;
    ResultSet rs;
            
    public manageTag() {
        initComponents();
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableOfTag = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTagName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cBoxTagCode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cBoxRelatedTag = new javax.swing.JComboBox<>();
        tId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtTagCode = new javax.swing.JTextField();
        txtRelatedTag = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 164, 246));

        TableOfTag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TagName", "TagCode", "RelatedTag"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableOfTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableOfTagMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableOfTag);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Tags");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name Of Tag :");

        txtTagName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTagName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Code Of Tag :");

        cBoxTagCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "lec_01", "tute_02", "lab_03" }));
        cBoxTagCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTagCodeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Related Tag :");

        cBoxRelatedTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "LECTURE", "TUTORIAL", "LAB" }));
        cBoxRelatedTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxRelatedTagActionPerformed(evt);
            }
        });

        tId.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("ID :");

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(187, 22, 22));
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(198, 24, 24), 4, true));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 116, 70));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 4, true));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(25, 25, 232));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(38, 38, 225), 4, true));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtTagCode.setEditable(false);
        txtTagCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTagCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTagCodeActionPerformed(evt);
            }
        });

        txtRelatedTag.setEditable(false);
        txtRelatedTag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRelatedTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelatedTagActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sajee\\Documents\\NetBeansProjects\\TimeTableManagement\\Refresh-icon_1.png")); // NOI18N
        btnRefresh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 16, 148), 4, true));
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTagName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtRelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cBoxTagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cBoxRelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(110, 110, 110)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTagName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxTagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxRelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(20, 20, 20)
                        .addComponent(btnDelete)
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTagNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTagNameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       DefaultTableModel table = (DefaultTableModel) TableOfTag.getModel(); 
       Connection conn = cObj.getConnection();
        
        if(TableOfTag.getSelectedRowCount() == 1)
        {
            try{                  
                    String deleteQuery = "delete from tag where ID='"+ tId.getText() +"' ";
                    pst = conn.prepareStatement(deleteQuery);

                    int response = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Delete", JOptionPane.YES_NO_OPTION);
                    if(response == JOptionPane.YES_OPTION)
                    {
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"ID: "+tId.getText()+" deleted successfully.");
                        
                        conn.close(); 
                    }
                }catch(Exception ex){

                } 
            //---for refresh / update Table---
            updateTable();
        }  
        else
        {   //---if table empty---
            if(TableOfTag.getRowCount() == 0)
            {
                JOptionPane.showMessageDialog(this, "Now, Table is Empty.");
            }
            //---if not select any row---
            else
            {
                   JOptionPane.showMessageDialog(this,"Please Select row.");
            }    
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        addTags addPage = new addTags();
        addPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel table = (DefaultTableModel) TableOfTag.getModel(); 
        if(TableOfTag.getSelectedRowCount()==1)
        {
            if(txtTagName.getText().isEmpty())
            JOptionPane.showMessageDialog(null,"Please Enter the Tag Name.");
            else if(txtTagCode.getText().isEmpty())
                JOptionPane.showMessageDialog(null,"Please Enter the Tag Code.");
            else if(txtRelatedTag.getText().isEmpty())
                JOptionPane.showMessageDialog(null,"Please Enter the Related Tag.");
            else
            {
                try {
                    Connection conn = cObj.getConnection();
                    String updateQuery = " Update tag Set TagName='"+txtTagName.getText()+"', TagCode='"+txtTagCode.getText()+"', RelatedTag='"+txtRelatedTag.getText()+"' Where ID='"+tId.getText()+"' ";
                    pst = conn.prepareStatement(updateQuery);
                    int response = JOptionPane.showConfirmDialog(null, "Are you sure to Update?", "UPDATE", JOptionPane.YES_NO_OPTION);
                    if(response == JOptionPane.YES_OPTION)
                    {   
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null,"ID: "+ tId.getText() + " Updated successfully.");
                    }
                    conn.close();

                } catch (SQLException ex) {
                    System.err.println("Go to an exception!!!");                              
                    JOptionPane.showConfirmDialog(null, ex.getMessage());
                }
                updateTable(); 
            }        
        }
        else
        {
            if(TableOfTag.getSelectedRow() == 0)
                JOptionPane.showMessageDialog(null,"Please Select row.");
            else
                JOptionPane.showMessageDialog(null,"Now, Table is Empty.");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void TableOfTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableOfTagMouseClicked
        DefaultTableModel table = (DefaultTableModel) TableOfTag.getModel();
        int selectedRow = TableOfTag.getSelectedRow();
        
        tId.setText(table.getValueAt(selectedRow, 0).toString());
        txtTagName.setText(table.getValueAt(selectedRow, 1).toString());
        txtTagCode.setText(table.getValueAt(selectedRow, 2).toString());
        txtRelatedTag.setText(table.getValueAt(selectedRow, 3).toString());

    }//GEN-LAST:event_TableOfTagMouseClicked

    private void txtTagCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTagCodeActionPerformed
        
    }//GEN-LAST:event_txtTagCodeActionPerformed

    private void txtRelatedTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelatedTagActionPerformed
       
    }//GEN-LAST:event_txtRelatedTagActionPerformed

    private void cBoxTagCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTagCodeActionPerformed
       txtTagCode.setText(cBoxTagCode.getSelectedItem().toString());
    }//GEN-LAST:event_cBoxTagCodeActionPerformed

    private void cBoxRelatedTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxRelatedTagActionPerformed
        txtRelatedTag.setText(cBoxRelatedTag.getSelectedItem().toString());
    }//GEN-LAST:event_cBoxRelatedTagActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        manageTag thisPage = new manageTag();
        thisPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRefreshActionPerformed

    //data get from database....
    public void getData()
    {
        try {
                Connection conn = cObj.getConnection();

                String q = " select * from tag ";
                pst = conn.prepareStatement(q);
                rs = pst.executeQuery();
                
                TableOfTag.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch (SQLException ex) {
            System.err.println("Go to an exception!!!");                              
            JOptionPane.showConfirmDialog(null, ex.getMessage());
        }
    }
    
     private void updateTable()
    {
        try{
            Connection conn = cObj.getConnection();
            String sql = "select * From tag";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            TableOfTag.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageTag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableOfTag;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cBoxRelatedTag;
    private javax.swing.JComboBox<String> cBoxTagCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tId;
    private javax.swing.JTextField txtRelatedTag;
    private javax.swing.JTextField txtTagCode;
    private javax.swing.JTextField txtTagName;
    // End of variables declaration//GEN-END:variables
}
